### ISSUE TITLE
VisibilityTimeout sendo alterada, mesmo sem preencher

### ISSUE THREAD

**Issue by andaraGui** [Coaktion/evolutty#48]
### Discussed in https://github.com/Coaktion/evolutty/discussions/47

<div type='discussions-op-text'>

<sup>Originally posted by **andaraGui** August  2, 2024</sup>
Caso não seja preenchido o campo visibilityTimeout do SQSClientOptions, a aplicação vai redefinir o visibilityTimeout da fila utilizando o padrão do evolutty (30s).

Trecho de código que faz a redefinição:
`VisibilityTimeout:           this.clientOptions.visibilityTimeout || DEFAULT_VISIBILITY_TIMEOUT,`

Acredito que o ideal seja que o parametro seja definido como obrigatório ou que não envie esse dado, caso não preenchido.

Isso pode trazer problemas de debugging, pois ele ignora o visibilityTimeout passado na Queue do serviço.</div>

**Comment by paulo-tinoco** [comment]
O Visibility Timeout é o tempo em que a aplicação espera a chegada de novas mensagens, dentro do polling... A AWS define 30 segundos como padrão. A ideia é que o desenvolvedor possa alterar isso de acordo com a sua necessidade. Mas caso ele não preencha, o valor será o padrão da AWS.

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html

**Comment by andaraGui** [comment]
Obrigado pela resposta, Tinoco!

A questão é que ela sobrescreve o Visibility TImeout configurado no SQS da AWS. Isso pode causar confusão por alterar o  Visibility TImeout  da fila sem que o parâmetro seja informado, já que ele não é obrigatório.

A ideia de criar a issue foi mais pra dar visibilidade caso alguém venha a ter o cenário de criar uma fila com um timeout maior que o default e isso gerar algum problema na execução.
