### ISSUE TITLE
[Bug]: MessageTranslator SQS não aceita translator personalizado

### ISSUE THREAD

**Issue by paulo-tinoco** [Coaktion/evolutty#49]
### Describe the bug

Identifiquei um problema no MessageTranslator da AWS e tentei extender com um Translator Customizado. Porém, mesmo passando dentro dos clientsOptions ele força o uso do padrão da lib.

### Your minimal, reproducible example

localstack

### Steps to reproduce

1. Criei meu arquivo de rotas
2. Criei uma classe MessageTranslator
3. Adicionei no `messageTranslator` do `SQSClientOptions`
4. Subir o serviço

### Expected behavior

Queria que usasse o `messageTranslator` do `SQSClientOptions`

### How often does this bug happen?

None

### Platform

Ubuntu 22.04

### Package version

v.2.1.2

**Comment by MatheusDev20** [comment]
Resolvido em [#50 ](url)
